/*

 KNIGHTS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Knights[] =
{
  0x7E,0x7E,0x7F,0x43,0xFF,0xA5,0xFF,0x81,
  0xFF,0xC3,0xFF,0x81,0xFF,0xFF,0xFF,0xFF,
  0x7E,0x7E,0x7F,0x5B,0xFF,0xBD,0xFF,0x99,
  0xFF,0xDB,0xC3,0xFF,0xFF,0xFF,0xFF,0xFF
};

/* End of KNIGHTS.C */
