/*

 SIMPLEBG_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\USER\Downloads\GameboyTools\gbtd22\simple_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define simplebg_mapWidth 40
#define simplebg_mapHeight 18
#define simplebg_mapBank 0

extern unsigned char simplebg_map[];

/* End of SIMPLEBG_MAP.H */
